Exclude Blank Recipient Address Values
Intelligent-Foods/intelligent-foods-ruby pull request #14
Opened 2023-09-12 19:46 UTC by imRohan

If the address value is an empty string, or nil, it should not be included in the request body during order creation. The current version of the Intelligent Foods Partner API raises an error if empty strings are included for any address field.

This change addresses the need by:
* Deleting any address keys from the JSON output if blank

2023-09-12 19:48 UTC, chriswoodford requested changes

2023-09-12 19:48 UTC, chriswoodford commented on lib/intelligent_foods/serializers/recipient_serializer.rb
> +      }.delete_if { |_k, v| v.blank? }
move this into a method and give it a name that describes what it's actually doing

2023-09-13 14:50 UTC, jmazur approved these changes

2023-09-13 15:08 UTC, chriswoodford approved these changes

2023-09-13 15:09 UTC, merged