Allow Callback URL and Headers to be Passed In
Intelligent-Foods/intelligent-foods-ruby pull request #23
Opened 2024-05-16 20:39 UTC by imRohan

During order creation, we should include optional params, callback_url and callback_headers. This will allow users to define a callback url which will be sent details of any changes to an order and its shipments.

This change addresses the need by:
* Updating the request body to include passed in callback_url and callback_headers

## Checklist Before A PR is Raised
Before raising a PR, you need to check and see if your PR:

- [ ] Meets issue expectations for functionality and implementation (Read the issue cards properly)

- [ ] Has the appropriate test coverage.

- [ ] Has no trailing whitespaces or typos.

- [ ] Has proper indentations.

Refer to the Guides for more information and ensure that your code meets
the requirements stated there.

## Raising a PR

When you're absolutely sure that your code satisfies all the checklist points
above, please delete the checklist and this paragraph. 
Raise a PR using the following template as your PR description:

```
PR Title(this should not be more than 50 characters)

This is a paragraph describing the circumstances that lead to this
commit being needed. You can think of it like the beginning of the
body of an email. It's about the "Why" and the intentions behind why we
needed to made this change. Keep this section wrapped at 72 characters.

This change addresses the need by:
* List the highlights of the changes made

Resolves #github-issue-number
```

2024-05-17 20:50 UTC, jmazur approved these changes

2024-05-30 18:03 UTC, chriswoodford requested changes
seems that there is an integration spec somewhere that should be passing in the callback_url at the very top of the stream. a request spec?

2024-06-07 20:45 UTC, chriswoodford requested changes

2024-06-07 20:45 UTC, chriswoodford commented on spec/factories.rb
> +    callback_headers { "Auth Bearer sd8ashidjkhj" }
these probably belong in a trait? as they are optional?

2024-06-13 20:53 UTC, chriswoodford approved these changes
my last review asked for an integration spec.. did you attempt that or

2024-06-14 16:05 UTC, chriswoodford requested changes
gotta follow the 4 phase test correctly

2024-06-14 16:05 UTC, chriswoodford commented on spec/intelligent_foods/resources/order_spec.rb
> +        result = JSON.parse(request.body)
https://thoughtbot.com/blog/four-phase-test

2024-06-14 18:08 UTC, chriswoodford approved these changes
this is much better. this is the standard

2024-06-14 18:08 UTC, chriswoodford commented on spec/support/api/schemas/order_with_callback.json
> +	"type" : "object",
fix spacing

2024-06-14 18:15 UTC, merged