Fix Client Instantiation
Intelligent-Foods/intelligent-foods-ruby pull request #24
Opened 2024-05-28 17:37 UTC by imRohan

Previously, a commit was merged which removed the class level memoization of the client. This solved an issue related to specs, but inherently changed how the IntelligentFoods authentication would work. In order to bring back the original authentication flow, and to fix the issues brought up in the original fix
(89d8fa59f74ded904a22f75db93e7b57bd0c50fd) this PR introduces a new method, #refresh_client, which can be used to create a new client object with a new client_id and client_secret.

This fix was tested using the same seed data as per the original commit:
```
bundle exec rspec
'./spec/intelligent_foods/resources/order_spec.rb[1:1:5:2]'
'./spec/intelligent_foods_spec.rb[1:5:1]' --seed 34813 --format d
```

This change addresses the need by:
* Introducing a #refresh_client method
* Refactoring specs to utilize the new method

2024-05-30 17:57 UTC, chriswoodford requested changes
this is fine as a quick fix/hack, but we should address the underlying issues in a future PR

2024-05-30 17:57 UTC, chriswoodford commented on lib/intelligent_foods.rb
> +      client
this breaks command/query separation. the code should ask for the client to be refreshed and then ask for the client

2024-05-31 21:37 UTC, jmazur approved these changes

2024-06-06 14:01 UTC, chriswoodford requested changes

2024-06-06 14:01 UTC, chriswoodford commented on spec/intelligent_foods_spec.rb
> +    IntelligentFoods.refresh_client
should refreshing the client be part of the configure method? we should probably always refresh when we configure?

2024-06-07 20:47 UTC, chriswoodford requested changes
this is much better but clean up your test

2024-06-07 20:47 UTC, chriswoodford commented on spec/intelligent_foods_spec.rb
> +    IntelligentFoods.refresh_client
you should remove this line now.. it's unnecessary, right?

2024-06-10 15:41 UTC, chriswoodford approved these changes

2024-06-10 17:05 UTC, merged